require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 160

Metrics/ClassLength:
  Max: 160

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - config/environments/**/*
    - config/routes.rb
    - lib/tasks/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    - db/migrate/**/*

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/PerceivedComplexity:
  Max: 23

Style/ClassAndModuleChildren:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
